name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build project
      run: dotnet build
    - name: Run unit tests and collect coverage
      run: dotnet test --no-build -l "junit;LogFilePath=test-results.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov\"
    - name: Generate coverage report
      run: |
        dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
        ./tools/reportgenerator -reports:tests/coverage.opencover.xml -targetdir:report
    - name: Print test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: tests/test-results.xml
    - name: Store coverage report as a build artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: report
        retention-days: 2
    - name: Publish coverage results to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: tests/coverage.info